include: {template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'}

osbuild-composer:
  image: quay.io/buildah/stable:latest
  script:
    - buildah bud -f osbuild-composer.Dockerfile -t "${CI_REGISTRY_IMAGE}:latest"
    - buildah push --creds "${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY_IMAGE}:latest"

ami-build:
  image: $CI_REGISTRY_IMAGE:latest
  services:
    - name: $CI_REGISTRY_IMAGE:latest
      alias: osbuild-composer
  before_script:
    - tail --follow --lines +1 "/builds/osbuild-composer-journal.txt" &
    - composer-cli() { /usr/bin/composer-cli --socket /builds/weldr-api.socket "$@"; }
    - echo "accessKeyID = \"${AWS_ACCESS_KEY_ID}\"" >> config.toml
    - echo "secretAccessKey = \"${AWS_SECRET_ACCESS_KEY}\"" >> config.toml
    - echo "region = \"${AWS_DEFAULT_REGION}\"" >> config.toml
  script:
    - composer-cli blueprints push moby.toml
    - compose_id=$(composer-cli --json compose start moby ami
      "moby-${CI_PIPELINE_ID}" config.toml | jq -r ".[].body.build_id")
    - while [[ $(composer-cli --json compose info "${compose_id}"
      | jq -r ".[].body.queue_status") =~ RUNNING|WAITING ]]; do sleep 15; done
